In [1]:
import pandas as pd
import os
import glob

In [2]:
data_2016_1_path = "data/Generacion_(kWh)_2016SEM1.xlsx"

In [3]:
df_2016sem1 = pd.read_excel(data_2016_1_path, skiprows=2)

In [4]:
df_2016sem1

,Fecha,Recurso,Tipo Generación,Combustible,Código Agente,Tipo Despacho,Es Menor,Es Autogenerador,0,1,...,15,16,17,18,19,20,21,22,23,Version
0,2016-01-01,AGUA FRESCA,HIDRAULICA,AGUA,ADCG,NO DESPACHADO CENTRALMENTE,SI,NO,3108.00,3079.20,...,4015.20,3967.20,3889.20,4899.60,5391.60,5337.60,5414.40,3820.80,3188.40,TX3
1,2016-01-01,ALBAN,HIDRAULICA,AGUA,EPSG,DESPACHADO CENTRALMENTE,NO,NO,3984.00,3952.00,...,3998.00,4002.00,3992.00,3994.00,3998.00,3980.00,3972.00,3974.00,3974.00,TX3
2,2016-01-01,AMOYA LA ESPERANZA,HIDRAULICA,AGUA,ISGG,DESPACHADO CENTRALMENTE,NO,NO,19380.00,19389.00,...,18817.00,18803.00,18474.00,18723.00,18661.00,18753.00,18776.00,18883.00,19047.00,TX3
3,2016-01-01,ASNAZU,HIDRAULICA,AGUA,GNCG,NO DESPACHADO CENTRALMENTE,SI,NO,209.44,149.66,...,85.20,92.35,107.53,218.68,293.65,248.22,195.91,145.04,100.76,TX3
4,2016-01-01,AYURA,HIDRAULICA,AGUA,EPMG,NO DESPACHADO CENTRALMENTE,SI,NO,5676.40,5674.87,...,5943.20,5941.67,5941.67,5943.20,5943.20,5941.67,5940.14,5941.67,5944.74,TX3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26122,2016-06-30,SAN FRANCISCO,HIDRAULICA,AGUA,EPMG,DESPACHADO CENTRALMENTE,NO,NO,NaN,NaN,...,NaN,1899.00,45266.00,85440.00,90641.00,90438.00,6069.00,NaN,NaN,TX4
26123,2016-06-30,TASAJERO 1,TERMICA,CARBON,TRMG,DESPACHADO CENTRALMENTE,NO,NO,NaN,NaN,...,163375.70,163430.20,163638.29,163312.64,163179.26,163443.59,163540.82,163430.33,163505.27,TX4
26124,2016-06-30,AUTOG YAGUARITO,TERMICA,BAGAZO,EMSG,NO DESPACHADO CENTRALMENTE,NO,SI,NaN,NaN,...,277.95,75.15,206.10,174.60,45.60,55.50,106.95,189.45,171.15,TX4
26125,2016-06-30,PROELECTRICA 1,TERMICA,GAS,PRIG,DESPACHADO CENTRALMENTE,NO,NO,NaN,NaN,...,NaN,NaN,6220.98,31663.91,42737.76,43790.28,43900.50,43881.30,42068.89,TX4
26126,2016-06-30,DARIO VALENCIA SAMPER,HIDRAULICA,AGUA,ENDG,DESPACHADO CENTRALMENTE,NO,NO,NaN,NaN,...,NaN,NaN,NaN,4336.02,30599.81,29008.81,9810.81,2387.84,NaN,TX4

In [ ]:
ruta_global = "data/Generacion_(kWh)_*.xlsx"
archivos_excel = glob.glob(ruta_global)

In [ ]:
import pandas as pd
import os
import glob

# Ruta donde están los archivos de Excel
ruta_archivos = "data/Generacion_(kWh)_*.xlsx"  # Cambia esto por la ruta real

# Función para detectar la fila del encabezado
def detectar_fila_header(archivo):
    df_temp = pd.read_excel(archivo, header=None)  # Leer sin encabezado
    
    for i, row in df_temp.iterrows():
        if "Fecha" in row.values:  # Detectar fila que contiene "Fecha"
            return i  # Devolver el índice de la fila con los encabezados reales
    
    return 0  # Si no se encuentra "Fecha", usar la primera fila por defecto

# Buscar todos los archivos Excel en la carpeta
archivos_excel = glob.glob(ruta_archivos)  # Ajusta la extensión si es necesario

# Lista para almacenar los DataFrames filtrados
dfs_filtrados = []

# Recorrer cada archivo y filtrar la información de JEPIRACHI (coincidencia parcial)
for archivo in archivos_excel:
    try:
        # Detectar la fila del encabezado dinámicamente
        fila_header = detectar_fila_header(archivo)
        
        # Leer el archivo con el encabezado detectado
        df = pd.read_excel(archivo, skiprows=fila_header)  

        # Limpiar nombres de columnas
        df.columns = df.columns.astype(str).str.strip()

        # Verificar si la columna "Recurso" existe antes de filtrar
        if "Recurso" not in df.columns:
            raise ValueError(f"El archivo {archivo} no contiene la columna 'Recurso'. Columnas encontradas: {df.columns.tolist()}")

        # Filtrar filas donde "Recurso" contenga "JEPIRACHI"
        df_jepirachi = df[df["Recurso"].str.contains("JEPIRACHI", case=False, na=False)]
        
        if not df_jepirachi.empty:
            dfs_filtrados.append(df_jepirachi)  # Agregar a la lista si tiene datos
        
        print(f"Procesado: {archivo} - Fila de encabezado: {fila_header} - Filas encontradas: {len(df_jepirachi)}")

    except Exception as e:
        print(f"Error procesando {archivo}: {e}")

# Unir todos los DataFrames en uno solo
df_consolidado = pd.concat(dfs_filtrados, ignore_index=True)

# Guardar en un archivo Excel (opcional)
# df_consolidado.to_excel("JEPIRACHI_consolidado.xlsx", index=False)

# También podrías guardarlo como CSV si lo prefieres
# df_consolidado.to_csv("JEPIRACHI_consolidado.csv", index=False)

# Mostrar un resumen del DataFrame consolidado
print(f"Total de filas consolidadas: {df_consolidado.shape[0]}")
df_consolidado.head()  # Muestra las primeras filas del DataFrame

Procesado: data/Generacion_(kWh)_2023.xlsx - Fila de encabezado: 2 - Filas encontradas: 281
Procesado: data/Generacion_(kWh)_2016SEM2.xlsx - Fila de encabezado: 2 - Filas encontradas: 159
Procesado: data/Generacion_(kWh)_2004.xlsx - Fila de encabezado: 1 - Filas encontradas: 335
Procesado: data/Generacion_(kWh)_2007.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2022.xlsx - Fila de encabezado: 2 - Filas encontradas: 363
Procesado: data/Generacion_(kWh)_2012.xlsx - Fila de encabezado: 2 - Filas encontradas: 366
Procesado: data/Generacion_(kWh)_2010.xlsx - Fila de encabezado: 2 - Filas encontradas: 364
Procesado: data/Generacion_(kWh)_2005.xlsx - Fila de encabezado: 1 - Filas encontradas: 364
Procesado: data/Generacion_(kWh)_2019.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2020.xlsx - Fila de encabezado: 2 - Filas encontradas: 151
Procesado: data/Generacion_(kWh)_2011.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2006.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2017SEM1.xlsx - Fila de encabezado: 2 - Filas encontradas: 70
Procesado: data/Generacion_(kWh)_2008.xlsx - Fila de encabezado: 2 - Filas encontradas: 366
Procesado: data/Generacion_(kWh)_2014.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2017SEM2.xlsx - Fila de encabezado: 2 - Filas encontradas: 110
Procesado: data/Generacion_(kWh)_SEM2_2018.xlsx - Fila de encabezado: 2 - Filas encontradas: 184
Procesado: data/Generacion_(kWh)_SEM1_2018.xlsx - Fila de encabezado: 2 - Filas encontradas: 181
Procesado: data/Generacion_(kWh)_2013.xlsx - Fila de encabezado: 2 - Filas encontradas: 364
Procesado: data/Generacion_(kWh)_2016SEM1.xlsx - Fila de encabezado: 2 - Filas encontradas: 182
Procesado: data/Generacion_(kWh)_2009.xlsx - Fila de encabezado: 2 - Filas encontradas: 365
Procesado: data/Generacion_(kWh)_2021.xlsx - Fila de encabezado: 2 - Filas encontradas: 364
Total de filas consolidadas: 6394

,Fecha,Recurso,Código Recurso,Tipo Generación,Combustible,Código Agente,Tipo Despacho,Es Menor,Clasificación,0,...,17,18,19,20,21,22,23,Version,Es Autogenerador,Tipo Generacion
0,2023-01-01 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,3368.03,...,9393.80,4689.14,2464.18,2663.03,2508.75,1790.45,1787.93,TX6,NaN,NaN
1,2023-01-02 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,866.68,...,6602.81,5630.79,4151.66,3076.85,3398.46,3014.56,3156.17,TX6,NaN,NaN
2,2023-01-03 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,2224.23,...,4945.84,4183.53,4101.65,2339.62,1136.66,1436.88,1622.28,TX6,NaN,NaN
3,2023-01-04 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,1151.30,...,6206.83,3769.32,2426.54,2688.43,3180.22,2750.54,1709.91,TX6,NaN,NaN
4,2023-01-05 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,2032.87,...,5327.68,4980.33,4109.21,3383.03,1998.07,2481.37,3095.92,TX6,NaN,NaN

In [2]:
df = pd.read_excel("JEPIRACHI_consolidado.xlsx")

In [3]:
df.head(3)

,Fecha,Recurso,Código Recurso,Tipo Generación,Combustible,Código Agente,Tipo Despacho,Es Menor,Clasificación,0,...,17,18,19,20,21,22,23,Version,Es Autogenerador,Tipo Generacion
0,2023-01-01 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,3368.03,...,9393.80,4689.14,2464.18,2663.03,2508.75,1790.45,1787.93,TX6,NaN,NaN
1,2023-01-02 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,866.68,...,6602.81,5630.79,4151.66,3076.85,3398.46,3014.56,3156.17,TX6,NaN,NaN
2,2023-01-03 00:00:00,JEPIRACHI 1 - 15,JPR1,EOLICA,VIENTO,EPMG,NO DESPACHADO CENTRALMENTE,SI,NORMAL,2224.23,...,4945.84,4183.53,4101.65,2339.62,1136.66,1436.88,1622.28,TX6,NaN,NaN

In [4]:
df.columns.to_list()

['Fecha',
 'Recurso',
 'Código Recurso',
 'Tipo Generación',
 'Combustible',
 'Código Agente',
 'Tipo Despacho',
 'Es Menor',
 'Clasificación',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 'Version',
 'Es Autogenerador',
 'Tipo Generacion']

In [26]:
columns_to_drop = ["Recurso", 'Tipo Generación', 'Combustible', 'Código Agente', 'Tipo Despacho', 'Es Menor', 'Clasificación','Version', 'Es Autogenerador', 'Tipo Generacion']
df = df.drop(columns=columns_to_drop, errors='ignore')

df.loc[:, '0':'23'] = df.loc[:, '0':'23'].fillna(0)
df['daily_KWh'] = df.loc[:, '0':'23'].sum(axis=1)
df['Código Recurso'] = df['Código Recurso'].ffill()

df['Fecha'] = pd.to_datetime(df['Fecha'])
df = df.sort_values(by='Fecha', ascending=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6394 entries, 440 to 280
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Fecha           6394 non-null   datetime64[ns]
 1   Código Recurso  6394 non-null   object
 2   0               6394 non-null   float64
 3   1               6394 non-null   float64
 4   2               6394 non-null   float64
 5   3               6394 non-null   float64
 6   4               6394 non-null   float64
 7   5               6394 non-null   float64
 8   6               6394 non-null   float64
 9   7               6394 non-null   float64
 10  8               6394 non-null   float64
 11  9               6394 non-null   float64
 12  10              6394 non-null   float64
 13  11              6394 non-null   float64
 14  12              6394 non-null   float64
 15  13              6394 non-null   float64
 16  14              6394 non-null   float64
 17  15              6394 non-null   float64
 18  16              6394 non-null   float64
 19  17              6394 non-null   float64
 20  18              6394 non-null   float64
 21  19              6394 non-null   float64
 22  20              6394 non-null   float64
 23  21              6394 non-null   float64
 24  22              6394 non-null   float64
 25  23              6394 non-null   float64
 26  daily_KWh       6394 non-null   float64
dtypes: datetime64[ns](1), float64(25), object(1)
memory usage: 1.4+ MB

In [28]:
df

,Fecha,Código Recurso,0,1,2,3,4,5,6,7,...,15,16,17,18,19,20,21,22,23,daily_KWh
440,2004-01-31,JPR1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,860.41,1904.59,2007.00,1342.35,672.68,486.94,830.31,900.59,1077.29,15060.93
441,2004-02-01,JPR1,1196.77,974.88,728.90,651.60,652.60,701.80,595.37,258.03,...,1830.29,1841.34,1049.18,911.63,549.19,606.42,712.84,484.93,438.75,17785.74
442,2004-02-02,JPR1,623.48,564.25,565.25,407.62,282.12,248.99,298.19,505.01,...,1905.59,1163.64,1047.17,1124.48,1072.27,999.98,1026.09,1163.64,936.73,22981.54
443,2004-02-03,JPR1,1044.16,842.36,584.33,696.78,1004.00,1020.06,889.54,1132.51,...,1921.66,1538.13,1822.26,1455.80,1539.13,1796.16,1701.78,1771.06,1484.92,31838.86
444,2004-02-04,JPR1,1432.71,1169.66,1158.62,844.36,471.88,1210.82,870.47,416.66,...,0.00,0.00,0.00,1801.18,1761.02,1611.42,1447.77,1430.70,1280.10,25818.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,2023-10-04,JPR1,0.00,0.00,0.00,0.00,128.48,0.00,46.23,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,44.07,0.00,4702.88
277,2023-10-05,JPR1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,102.80,84.54,375.25
278,2023-10-06,JPR1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1089.59,1735.49,1754.29,1099.84,1007.42,652.52,618.68,691.09,646.92,12428.02
279,2023-10-07,JPR1,1372.96,1401.26,540.31,377.83,19.93,0.00,0.00,0.00,...,0.00,181.77,2199.55,2451.77,2549.16,2648.93,776.23,231.03,0.00,26279.47
280,2023-10-08,JPR1,3.80,0.00,0.00,0.00,0.00,336.40,629.35,289.06,...,6439.86,5250.77,2065.49,113.47,53.54,0.00,19.56,0.00,0.00,32516.74

In [29]:
df_mensual = df.copy()
df_mensual['Año-Mes'] = df_mensual['Fecha'].dt.to_period('M')
df_mensual = df_mensual.groupby('Año-Mes', as_index=False)['daily_KWh'].sum()

In [32]:
df_mensual

     Año-Mes   daily_KWh
0    2004-01    15060.93
1    2004-02  1630762.21
2    2004-03  3947269.58
3    2004-04  4669053.22
4    2004-05  6122227.17
..       ...         ...
212  2023-06  3161868.80
213  2023-07  4555233.68
214  2023-08  2875975.93
215  2023-09  3145814.69
216  2023-10   165407.82

[217 rows x 2 columns]